ravuAlHemioSharpIrcBot_counters_overview:
    path:     /counters
    controller: 'RavuAlHemioSharpIrcBotWebBundle\Counters::overview'

ravuAlHemioSharpIrcBot_counters_details:
    path:     /counters/{strCommand}
    controller: 'RavuAlHemioSharpIrcBotWebBundle\Counters::details'

ravuAlHemioSharpIrcBot_quotes_topQuotes:
    path:     /topquotes
    controller: 'RavuAlHemioSharpIrcBotWebBundle\Quotes::topQuotes'

ravuAlHemioSharpIrcBot_quotes_quotesVotes:
    path:     /quotesvotes
    controller: 'RavuAlHemioSharpIrcBotWebBundle\Quotes::quotesVotes'

ravuAlHemioSharpIrcBot_thanks_thanksGrid:
    path:     /thanks
    controller: 'RavuAlHemioSharpIrcBotWebBundle\Thanks::thanksGrid'

ravuAlHemioSharpIrcBot_nickMapping_nicksAliases:
    path:    /nicks-aliases
    controller: 'RavuAlHemioSharpIrcBotWebBundle\NickMapping::nicksAliases'

ravuAlHemioSharpIrcBot_nickMapping_aliasesForNick:
    path:    /aliases
    controller: 'RavuAlHemioSharpIrcBotWebBundle\NickMapping::aliasesForNick'
