services:
  RavuAlHemio\SharpIrcBotWebBundle\Controller\CountersController:
    bind:
      $objEM: '@doctrine.orm.default_entity_manager'
      $objTwig: '@twig'
      $objRouter: '@router.default'
    tags: ['controller.service_arguments']
  RavuAlHemio\SharpIrcBotWebBundle\Controller\NickMappingController:
    bind:
      $objEM: '@doctrine.orm.default_entity_manager'
      $objTwig: '@twig'
    tags: ['controller.service_arguments']
  RavuAlHemio\SharpIrcBotWebBundle\Controller\QuotesController:
    bind:
      $objEM: '@doctrine.orm.default_entity_manager'
      $objTwig: '@twig'
    tags: ['controller.service_arguments']
  RavuAlHemio\SharpIrcBotWebBundle\Controller\ThanksController:
    bind:
      $objEM: '@doctrine.orm.default_entity_manager'
      $objTwig: '@twig'
    tags: ['controller.service_arguments']
